---
# defaults file for vector-role
vector_version: "0.21.0"
vector_config_path: /etc/vector/vector.yaml
vector_data_dir: /var/lib/vector
vector_disable_gpg_check: true
vector_config: {}

# ClickHouse variables (used in production)
clickhouse_user: netology
clickhouse_password: netology
clickhouse_host: clickhouse-01
