---
# tasks file for vector-role
- name: Include install tasks
  include_tasks: install_vector.yml

# Создание каталога для vector
- name: Creates directory
  become: true
  file:
    path: "{{ vector_data_dir | default('/var/lib/vector') }}"
    state: directory
    owner: "{{ ansible_user_id | default('root') }}"
    group: "{{ ansible_user_gid | default('root') }}"
    mode: 0755

- name: Deploy config Vector
  ansible.builtin.template:
    src: vector.j2
    dest: "{{ vector_config_path }}"
    mode: 0644
    owner: "{{ ansible_user_id | default('root') }}"
    group: "{{ ansible_user_gid | default('root') }}"
    validate: vector validate --no-environment --config-yaml %s
  become: true
  notify: Start Vector service
  when: vector_config is defined and vector_config != {}

- name: Create systemd unit Vector
  become: true
  template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644

- name: Start Vector service
  become: true
  systemd:
    name: vector
    state: started
    daemon_reload: true
    enabled: yes
