---
galaxy_info:
  author: viktor
  description: Vector role for log shipping
  company: netology
  role_name: vector
  namespace: yc
  license: MIT
  min_ansible_version: 2.8
  
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy
    - name: EL
      versions:
        - 7
        - 8
    - name: OracleLinux
      versions:
        - 8
  
  galaxy_tags:
    - vector
    - logging
    - observability
    - timber
    - logs

dependencies: []
